# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hexa < Formula
  desc "Hexactitude CLI - Unified automation and scripting toolkit"
  homepage "https://github.com/hyphaene/hexa"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hyphaene/hexa/releases/download/v0.1.2/hexa_Darwin_x86_64.tar.gz"
      sha256 "d842b33eae3ff4d19a48e3e6b98e1e95eda503b37dc9607053e19164060424bf"

      def install
        bin.install "hexa"
        bin.install_symlink bin/"hexa" => "hw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hyphaene/hexa/releases/download/v0.1.2/hexa_Darwin_arm64.tar.gz"
      sha256 "2a534358278317c81ce0eb89dec4325981c562b3f5ad1cc8bac6b19af6310517"

      def install
        bin.install "hexa"
        bin.install_symlink bin/"hexa" => "hw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hyphaene/hexa/releases/download/v0.1.2/hexa_Linux_x86_64.tar.gz"
      sha256 "f01cdc2003f387b740a0aeb220868c650e0027d22ffc63a4daf39d8beb42f49f"
      def install
        bin.install "hexa"
        bin.install_symlink bin/"hexa" => "hw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hyphaene/hexa/releases/download/v0.1.2/hexa_Linux_arm64.tar.gz"
      sha256 "55eb9e9419882160d546b9707462fe0dead427b17ad428a1acec19c40b0f3393"
      def install
        bin.install "hexa"
        bin.install_symlink bin/"hexa" => "hw"
      end
    end
  end

  test do
    system "#{bin}/hexa", "--help"
    system "#{bin}/hw", "--help"
  end
end
