# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hexa < Formula
  desc "Hexactitude CLI - Unified automation and scripting toolkit"
  homepage "https://github.com/hyphaene/hexa"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hyphaene/hexa/releases/download/v0.6.0/hexa_Darwin_x86_64.tar.gz"
      sha256 "4396b59172904ef2c859c8ac0d164dd9d756152f2b4c4d564713cfeb82d4ea48"

      def install
        bin.install "hexa"
        bin.install_symlink bin/"hexa" => "hw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hyphaene/hexa/releases/download/v0.6.0/hexa_Darwin_arm64.tar.gz"
      sha256 "c98f7f4a67adbb8d7a60908f04bcc4d1eaaac826b7e2fdaf9e484ed074cd981b"

      def install
        bin.install "hexa"
        bin.install_symlink bin/"hexa" => "hw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hyphaene/hexa/releases/download/v0.6.0/hexa_Linux_x86_64.tar.gz"
      sha256 "6b62e92a0071a20127be1e467d84d5839051fa5863f7d1f77fa9fa34b974983b"
      def install
        bin.install "hexa"
        bin.install_symlink bin/"hexa" => "hw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hyphaene/hexa/releases/download/v0.6.0/hexa_Linux_arm64.tar.gz"
      sha256 "68debfd79e9856573d59aa8c41d9fd3f29ca1647fed5a3457f6b20373ad0d7f2"
      def install
        bin.install "hexa"
        bin.install_symlink bin/"hexa" => "hw"
      end
    end
  end

  test do
    system "#{bin}/hexa", "--help"
    system "#{bin}/hw", "--help"
  end
end
