# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hexa < Formula
  desc "Hexactitude CLI - Unified automation and scripting toolkit"
  homepage "https://github.com/hyphaene/hexa"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hyphaene/hexa/releases/download/v0.1.7/hexa_Darwin_x86_64.tar.gz"
      sha256 "60b498e7cf639819a8f6854d02708f666c8d3f844ed07dc7ac157d4d7727567e"

      def install
        bin.install "hexa"
        bin.install_symlink bin/"hexa" => "hw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hyphaene/hexa/releases/download/v0.1.7/hexa_Darwin_arm64.tar.gz"
      sha256 "5531528b655be3dc5b13144b73059734d1babda86a8b559f410eee2deab9721a"

      def install
        bin.install "hexa"
        bin.install_symlink bin/"hexa" => "hw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hyphaene/hexa/releases/download/v0.1.7/hexa_Linux_x86_64.tar.gz"
      sha256 "3806ae68f0be406e970887acc72a3d4da0b26d834d249614e689097506cf9748"
      def install
        bin.install "hexa"
        bin.install_symlink bin/"hexa" => "hw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hyphaene/hexa/releases/download/v0.1.7/hexa_Linux_arm64.tar.gz"
      sha256 "8ab161f2174cbfa88d16e26a775c989f70885f0420a7f5ae040a75a5aa3dadb0"
      def install
        bin.install "hexa"
        bin.install_symlink bin/"hexa" => "hw"
      end
    end
  end

  test do
    system "#{bin}/hexa", "--help"
    system "#{bin}/hw", "--help"
  end
end
